### ISSUE TITLE
getMailItemMimeContent not returning any response when size limit exceeded

### ISSUE THREAD

**Issue by koonal19** [davecra/easyEWS#13]
@davecra @vsamtani  When trying to get the MimeContent of a large (>1MB) email through easyEws getMailItemMimeContent on Mac, there is no response from easyEws, neither a success nor failure (expected) response.
Till 29th oct, atleast it was able to throw error – "makeEwsRequestAsync failed. [object Object]"

Outlook mac client 16.42 version [Office 2019]

**Comment by davecra** [comment]
Based on the description, if it was working, and now it is not, and as there have been no recent changes to easyEws, it might be caused by a change in the API, the Mac Outlook application or Exchange Online (or Exchange Server if you are on-prem). 
Next step is to determine where the failure is...

If you have access to Outlook for Windows and Outlook from the web, can you test there. Do you see a similar issue? 
If you do, please see what happens when you run your EWS SOAP request from a simple service tester like https://restape.com/. Do you get a different error maybe from EWS? Or, does it work fine?

- If you do get a different error using EWS directly, then the problem is with a change to Exchange
- If it worked from the direct EWS call, but fails on all the clients, then the problem is likely based on a change to the makeEwsRequestAsync function in OfficeJS.
- If it works from all the clients, but ONLY fails on the Mac Office client, then there is likely an issue with some update to the Mac Office client that is stopping the error or the request from functioning as it previously did.

In any of these cases you would have enough information to pinpoint where and my suggestion is two-fold:

1) Submit your results to https://stackoverflow.com/questions/tagged/office-js. This will directly inform the Product Group of the issue.
2) Send me a link to your stackoverflow request and I can send it along to my contacts as well.

**Comment by kratikal-archit** [comment]
Is there any solution to this. I am also facing the same issue on a windows device.

**Comment by davecra** [comment]
The limit of 1mb is a known issue with the officejs libraries and the makeEwsRequestAsync() command. This is not a limitation of easyEws. Not getting an error as the original poster suggested is a problem, but the limit of >1mb is a built in limitation from the Office Developer team in officejs. If you want to have a greater limit than 1mb, I would suggest posting in stack overflow and asking the product team to allow a larger size. The more folks that ask for it, the more likely it will be fixed.

**Comment by architjn** [comment]
Thank you david. But can you atleast fix the error output as it shows [object Object]. At least we will be able to know what's happening. Thanks
