### ISSUE TITLE
Speed up delete email?

### ISSUE THREAD

**Issue by hazcod** [davecra/easyEWS#15]
Hi!

Thank you for your library! I am using version `.20`.
Is there a way to speed up the visual feedback after moving an email to the deleted items folder?
This takes around 5 seconds at this point, but would love to have this faster for the user.

```js
        easyEws.moveItem(boxItem.itemId, "deleteditems", function() {
          Office.context.ui.closeContainer();
        }, function(error) {
          console.log(error);
        });
```

**Comment by davecra** [comment]
This is a function of Outlook versus Outlook Online and not because of the library.
The issue is that full Outlook client is running in CACHED mode versus ONLINE mode. Because you are moving or deleting the item in Outlook full client you have to wait for the cache agent to fire to display the update. If you run this in Outlook Online, you will see the change is instant because the web client is ONLINE all the time.
Unfortunately this is a top requested item. I would go to the StackExchange and request this an option to force a cache operation in Outlook full clients: https://stackoverflow.com/questions/tagged/office-js
