### ISSUE TITLE
all the file dates are the same?

### ISSUE THREAD

**Issue by gitcnd** [davecra/easyEWS#18]
Usually we can work out if 1.0.20 is newer than 1.0.3 by files dates... unless you do something sketchy which breaks all of them?
```

$ unzip -v easyEWS-master.zip
Archive:  easyEWS-master.zip
037d7db302e5e2c4d0da9fcd1654b4b248d00795
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
       0  Stored        0   0% 03-01-2021 15:07 00000000  easyEWS-master/
      56  Defl:N       54   4% 03-01-2021 15:07 0d97764f  easyEWS-master/.npmignore
   35141  Defl:N    12128  66% 03-01-2021 15:07 ec4c468e  easyEWS-master/LICENSE
   37141  Defl:N     7584  80% 03-01-2021 15:07 097a2437  easyEWS-master/README.md
      25  Defl:N       24   4% 03-01-2021 15:07 a3fd9d7a  easyEWS-master/_config.yml
   73813  Defl:N    12628  83% 03-01-2021 15:07 a34c925f  easyEWS-master/easyEws.js
   17042  Defl:N     4382  74% 03-01-2021 15:07 7576e298  easyEWS-master/easyEws.min.js
   58224  Defl:N     8999  85% 03-01-2021 15:07 cf173bb6  easyEWS-master/easyEws1.0.10.js
   13594  Defl:N     3220  76% 03-01-2021 15:07 4e11769b  easyEWS-master/easyEws1.0.10.min.js
   61767  Defl:N     9674  84% 03-01-2021 15:07 21d31b67  easyEWS-master/easyEws1.0.11.js
   14373  Defl:N     3451  76% 03-01-2021 15:07 0678fa0b  easyEWS-master/easyEws1.0.11.min.js
   61618  Defl:N     9657  84% 03-01-2021 15:07 2a93b697  easyEWS-master/easyEws1.0.12.js
   14389  Defl:N     3448  76% 03-01-2021 15:07 7f9c0557  easyEWS-master/easyEws1.0.12.min.js
   64790  Defl:N    10257  84% 03-01-2021 15:07 0e2afd11  easyEWS-master/easyEws1.0.14.js
   15416  Defl:N     3726  76% 03-01-2021 15:07 ccadae5a  easyEWS-master/easyEws1.0.14.min.js
   67159  Defl:N    10946  84% 03-01-2021 15:07 3eb5f3ec  easyEWS-master/easyEws1.0.15.js
   15772  Defl:N     3938  75% 03-01-2021 15:07 6ef3c3f4  easyEWS-master/easyEws1.0.15.min.js
   68115  Defl:N    11278  83% 03-01-2021 15:07 bd06c03f  easyEWS-master/easyEws1.0.16.js
   15858  Defl:N     4001  75% 03-01-2021 15:07 70dfe430  easyEWS-master/easyEws1.0.16.min.js
   70423  Defl:N    11586  84% 03-01-2021 15:07 4097e3fd  easyEWS-master/easyEws1.0.17.js
   16029  Defl:N     4058  75% 03-01-2021 15:07 2d4b6678  easyEWS-master/easyEws1.0.17.min.js
   70448  Defl:N    11598  84% 03-01-2021 15:07 ae70c0a5  easyEWS-master/easyEws1.0.18.js
   16032  Defl:N     4058  75% 03-01-2021 15:07 8956002d  easyEWS-master/easyEws1.0.18.min.js
   70458  Defl:N    11604  84% 03-01-2021 15:07 4022f1db  easyEWS-master/easyEws1.0.19.js
   16042  Defl:N     4061  75% 03-01-2021 15:07 75ef815c  easyEWS-master/easyEws1.0.19.min.js
   20045  Defl:N     3862  81% 03-01-2021 15:07 86e3788b  easyEWS-master/easyEws1.0.2.js
   73813  Defl:N    12628  83% 03-01-2021 15:07 a34c925f  easyEWS-master/easyEws1.0.20.js
   17042  Defl:N     4382  74% 03-01-2021 15:07 7576e298  easyEWS-master/easyEws1.0.20.min.js
   24828  Defl:N     3820  85% 03-01-2021 15:07 5abc42cc  easyEWS-master/easyEws1.0.3.js
   29728  Defl:N     4536  85% 03-01-2021 15:07 565f66ce  easyEWS-master/easyEws1.0.4.js
   26146  Defl:N     3933  85% 03-01-2021 15:07 75e3971c  easyEWS-master/easyEws1.0.5.js
   38384  Defl:N     5712  85% 03-01-2021 15:07 fa6ddf2d  easyEWS-master/easyEws1.0.6.js
   43597  Defl:N     6844  84% 03-01-2021 15:07 93f94ae9  easyEWS-master/easyEws1.0.7.js
   43733  Defl:N     6866  84% 03-01-2021 15:07 a8f4fb06  easyEWS-master/easyEws1.0.8.js
   43861  Defl:N     6861  84% 03-01-2021 15:07 43f3d050  easyEWS-master/easyEws1.0.9.js
    1582  Defl:N      621  61% 03-01-2021 15:07 c0745967  easyEWS-master/npm-debug.log
     604  Defl:N      321  47% 03-01-2021 15:07 4a08095a  easyEWS-master/package.json
--------          -------  ---                            -------
 1257088           226746  82%                            37 files
```

**Comment by davecra** [comment]
Not sure why this happened. It might have been from a merge, but there is not anything I am aware of that can fix this that I am aware of. Do you have any ideas on how to fix it?

**Comment by gitcnd** [comment]
FYI - it's a pretty significant mistake - loads of products rely on dates being real (especially all "Make" systems), and using fake ones breaks a lot of stuff (or it indicates that someone has done something they probably should not have, and are trying to cover their tracks).

**Comment by davecra** [comment]
I pulled down my repo as a ZIP and extracted and everything was marked the same date as well. It was todays date, like right now. I also pulled down another repro as a zip and saw the same thing (https://github.com/kevinsqi/react-circular-progressbar). I also tried with a few of yours too, to see if maybe there was something different going on. But saw the same. As best I can tell, this appears to be because GitHub is not placing the original file check-in date in the ZIP or CLONE output. I also tried doing a GIT CLONE on the my repo and the react repo I used as a sample and I got the same exact thing. All the files in the repo are the same (todays date). 

Looking for an answer, I found this:
https://stackoverflow.com/questions/21735435/git-clone-changes-file-modification-time

> Git does not record timestamp for the files, since it is a Distributed VCS (meaning the time on your computer can be different from mine: there is no "central" notion of time and date)
> The official argument for not recording that metadata is explained in this answer. (https://stackoverflow.com/questions/1964470/whats-the-equivalent-of-subversions-use-commit-times-for-git/1964508#1964508)
> But you can find scripts which will attempt to restore a meaningful date, like this one (or a simpler version of the same idea).

It suggests using a script like this to get a more meaningful answer from GIT:
https://stackoverflow.com/questions/1964470/whats-the-equivalent-of-subversions-use-commit-times-for-git/13284229#13284229

Another suggests is to verify the file dates you need to GIT CLONE the repo, then use GIT LOG and then keep pressing enter you can go through the whole repro log to verify file dates if you are concerned with repro content.

I know it is not the same as the file date, but for my REPRO you can also see the file date and version information in the header of the file and the repro shows the CRC and the check-in date for comparison. If you look at the repro in general however, you can see the commit dates are in order to their versioning. 

Outside of that it appears this is a limit of the file date mechanism and the OS and not anything any repro owner such as ourselves can manage.
