### ISSUE TITLE
updateEwsHeader not working with Office 2019 VL build 1808 10378.20029

### ISSUE THREAD

**Issue by matt6697** [davecra/easyEWS#19]
When using the **updateEwsHeader** function in Office 2019 VL build 1808 10378.20029, the Internet Header is correctly set by the function on the EWS server but is overwritten by Outlook 2019 when the email is sent => no Internet Header is present in the mail beeing effectively sent. Office 2019 is used in **online** mode in both scenarios.

If I keep the draft open in outlook, open OWA, and send the email from OWA, the Internet Headers are correctly set; It seems that Outlook 2019 VL doesn't update the opened draft after the makeEwsRequestAsync UpdateItem. Everything works perfectly with Outlook 2019 retail (latest build) in Office 365.

Office 2019 retail introduced API 1.8 support with a new setCustomHeaders  function which I can't use as Office 2019 VL is required for licence activation with enterprise KMS server.

Does the **updateEwsHeader** function work with Outlook versions not supporting addin API 1.8 (Outlook 2016 or Outlook 2019 1808) ?

**Comment by davecra** [comment]
This is a function of Outlook versus Outlook Online and not because of the library.

The issue is that full Outlook client is running in CACHED mode versus ONLINE mode. Because you are moving, updating or deleting the item in Outlook full client you have to wait for the cache agent to fire to display the update. If you run this in Outlook Online, you will see the change is instant because the web client is ONLINE all the time.

Unfortunately this is a top requested item. I would go to the StackExchange and request this an option to force a cache operation in Outlook full clients: https://stackoverflow.com/questions/tagged/office-js
