### ISSUE TITLE
Recipient could be undefined/other

### ISSUE THREAD

**Issue by naemcivic** [davecra/easyEWS#4]
Issue: Recipient/Group/DL can actually be `undefined` or `other` which can be missed while trying to expand DL/Group

potential fix could be including a conditional for the check to include:

```recip.recipientType == undefined``` and ```recip.recipientType == Office.MailboxEnums.RecipientType.Other``` 

Please take a look at the following lines:
https://github.com/davecra/easyEWS/blob/master/easyEws.js#L790
https://github.com/davecra/easyEWS/blob/master/easyEws.js#L837
https://github.com/davecra/easyEWS/blob/master/easyEws.js#L884

Here is a stackoverflow post by one of our old dev: https://stackoverflow.com/questions/57531207/office-js-recipienttype-discrepancy-for-outlook-on-windows

**Comment by davecra** [comment]
Confirmed per the PG this is a known issue and its possible fix/resolution is on backlog. 

The prescribed workaround is to actually call ResolveNames on each recipientType that is not returned as "user" or "distributionList." This way you will get a definitive result on each one. It does not make sense to make that call in the expandGroups function for performance reasons so adding it there would not be productive. 

My current suggestion is to loop through the results and then call ResolveNames on each one (although there is no mechanism for "other" and "undefined". Also, the "resolveRecipient" function was added to easyEws in v1.0.11 (https://github.com/davecra/easyEWS#resolveRecipient).

Please advise, but I believe the best change would be on getAllRecipientsAsync() to have the successCallback return three groupings instead of TWO:

- groups[]
- users[]
- other[] <-- this contains "undefined" and "other"

You can then loop through the "undefined" and "other" grouping calling "resolveRecipient" to update the MailItems one by one. It is slower, but will provide correct results. Also, this would not interfere with future plans once/if the PG updates the recipientType accuracy.

**Comment by naemcivic** [comment]
Thank you for your suggestion David. Will need to further discuss refactoring with the team to use the new api function `resolveRecipient` in the update on v1.0.11. Will be closing this issue.
